name: armTemplateDeployment

on:
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy resource group rg-githubactions with az cli
        uses: Azure/cli@v1
        with:
          inlinescript: |
            az deployment sub create --location "UK South" --template-file ./arm-templates/resourcegroup.json
